language: php
php:
 - '7.2'

 env:
  global:
    - CC_TEST_REPORTER_ID=4258b38823d2c1c860b0d96a8af0629fef59f99eee31edd139848cd19aca0d5e

install:
 - make install
 - travis_retry composer install --no-interaction --no-suggest

 before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: 
 - composer test -- --coverage-clover=coverage.xml

#after_script:

after_success:
# Submit coverage report to https://codecov.io
#- bash <(curl -s https://codecov.io/bash)
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
