name: PHP CI
with:
  super_secret: ${{ secrets.MySecret }}

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install
      run: make install

    - name: Run linter
      run: make lint

    - name: Run test & publish code coverage
      uses: paambaati/codeclimate-action@v2.5.3
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.MySecret }}
      with:
        coverageCommand: make test
        debug: true
